[package]
name = "thud"
version = "0.1.0"
authors = ["Stu Black"]

[dependencies]
gtk = "0.0.6"
cairo-rs = "0.0.7"
rand = "0.3.12"

[[bin]]
name = "console"

[[bin]]
name = "gtk"

[[bin]]
name = "board_to_image"

[[bin]]
name = "console_mcts"
