* Overview

This package provides an implementation of the game Thud (as described at
http://discworld.wikia.com/wiki/Thud_(game)). It contains provisional code for
console- and GTK-based UIs and an AI based on Monte Carlo tree search. (Note
that naive Monte Carlo tree search is known not to be a very good algorithm for
playing games like Thud. This codebase is intended as a platform for exploring
why that is so.)

** Data structures

The =search_graph= module provides a general-purpose, rollout-based DAG-like
data structure. It may be used to explore the state space of a game tree
compactly (through the use of transposition tables), with support for cycle
detection and edge- and vertex-specific data. It is a prime candidate for being
factored out into its own data structure.

** Algorithms

The =mcts= module provides a preliminary implementation of Monte Carlo tree
search for the game of Thud. It may eventually be factored out into a more
generic library for rollout-based move planning.

* Copyright

Copyright 2015-2016, Donald S. Black.

Licensed under the Apache License, Version 2.0 (the “License”); you may not use
this file except in compliance with the License. You may obtain a copy of the
License at http://www.apache.org/licenses/LICENSE-2.0.

Unless required by applicable law or agreed to in writing, software distributed
under the License is distributed on an “AS IS” BASIS, WITHOUT WARRANTIES OR
CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.

* Legal disclaimer

"Thud", "Discworld", and related terms are not my intellectual property.
