[package]
name = "thud-ui-common"
version = "0.1.0"
authors = ["Stu Black"]
edition = "2018"

[dependencies]
chrono = "0.4"
clap = "2.33"
fern = "0.5"
log = "0.4"
mcts = { path = "../mcts" }
rand = "0.7.0"

[dependencies.thud-game]
path = "../thud_game"
features = ["ai"]
