[package]
name = "thud-ui-common"
version = "0.1.0"
authors = ["Stu Black"]

[dependencies]
chrono = "0.2.*"
clap = "2.2.*"
fern = "0.3.5"
log = "0.3.5"
mcts = { path = "../mcts" }
rand = "0.3.12"

[dependencies.thud-game]
path = "../thud_game"
features = ["ai"]
