[package]
name = "mcts"
version = "0.1.0"
authors = ["Stu Black"]

[dependencies]
itertools = "0.8"
log = "0.4.6"
rand = "0.6.1"
search-graph = { git = "https://github.com/dstu/search-graph.git", branch = "master" }
