[package]
name = "mcts"
version = "0.1.0"
authors = ["Stu Black"]

[dependencies]
itertools = "0.4.*"
log = "0.3.5"
rand = "0.3.12"
search-graph = { git = "https://github.com/dstu/search-graph.git", branch = "master" }
